/**
 * Index every numbered ruling to the place it is actually explained.
 *
 *   npm run rulings           rewrite docs/RULINGS.md
 *   npm run rulings -- --check  fail if it is out of date (gate G8)
 *
 * Rulings are cited from code as R07, R42, R86. Thirty-nine of them were cited
 * and defined in neither design document, while CLAUDE.md sent readers to
 * docs/DIRECTION.md "for R19-R55" -- a pointer to a document that does not
 * contain them. Someone reading `// R63` in a diff had nowhere to go.
 *
 * The fix is not to invent the missing prose. Every one of those rulings IS
 * explained, in the comment that cites it, written when the decision was made;
 * what was missing is a way to find it. So this is generated, never authored:
 * it says where each ruling lives and quotes its first line, and it cannot
 * drift, because the gate regenerates it and compares.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { appSources, readDoc, ROOT } from './lib/source-scan';

const CITE = /\bR(\d{2})\b/g;

type Cite = { ruling: number; path: string; line: number; text: string };

/** Where the design documents define a ruling outright. */
function definedInDocs(): Map<number, string> {
  const out = new Map<number, string>();
  for (const doc of ['docs/DIRECTION.md', 'docs/REDESIGN.md']) {
    const lines = readDoc(doc).split('\n');
    lines.forEach((line, i) => {
      const m = /^(?:### R(\d{2,3})|- \*\*R(\d{2,3})\*\*|\*\*R(\d{2,3})\*\*)/.exec(line);
      const n = m?.[1] ?? m?.[2] ?? m?.[3];
      if (n) out.set(Number(n), `${doc}:${i + 1}`);
    });
  }
  return out;
}

/**
 * Citations in code. The line recorded is the citation itself, because that is
 * the line a reader lands on; the quoted text is trimmed of comment syntax so
 * the index reads as prose rather than as punctuation.
 */
function citations(): Cite[] {
  const out: Cite[] = [];
  const files = [...appSources().map((f) => f.path), 'scripts/screenshots.ts', 'scripts/gate.ts'];
  const seen = new Set<string>();
  for (const path of files) {
    if (seen.has(path)) continue;
    seen.add(path);
    let raw: string;
    try {
      raw = readFileSync(join(ROOT, path), 'utf8');
    } catch {
      continue;
    }
    raw.split('\n').forEach((line, i) => {
      for (const m of line.matchAll(CITE)) {
        out.push({
          ruling: Number(m[1]),
          path,
          line: i + 1,
          text: line.replace(/^\s*(\/\*+|\*+\/?|\/\/|\{\/\*)\s?/, '').replace(/\s*\*\/\s*$/, '').trim(),
        });
      }
    });
  }
  // globals.css is not TypeScript and carries several rulings of its own.
  readDoc('app/globals.css')
    .split('\n')
    .forEach((line, i) => {
      for (const m of line.matchAll(CITE)) {
        out.push({
          ruling: Number(m[1]),
          path: 'app/globals.css',
          line: i + 1,
          text: line.replace(/^\s*(\/\*+|\*+\/?)\s?/, '').trim(),
        });
      }
    });
  return out;
}

function render(): string {
  const docs = definedInDocs();
  const cites = citations();
  const rulings = [...new Set([...docs.keys(), ...cites.map((c) => c.ruling)])].sort((a, b) => a - b);

  const lines: string[] = [
    '# Rulings index',
    '',
    '**Generated by `npm run rulings`. Do not edit by hand** — gate G8 regenerates',
    'this file and fails if it differs.',
    '',
    'Numbered design rulings are cited from code as `R07`, `R42`, `R86`. Many are',
    'argued at length in [docs/DIRECTION.md](DIRECTION.md) and',
    '[docs/REDESIGN.md](REDESIGN.md); many others were decided in the comment that',
    'cites them and were never written up anywhere else. That is not ideal, but it',
    'is honest, and it is better than prose invented after the fact to fill a',
    'table. This index says, for every ruling, where to go.',
    '',
    `${rulings.length} rulings. ${docs.size} argued in a design document; the rest are`,
    'defined at their first citation.',
    '',
    '| Ruling | Argued in | Cited from |',
    '|---|---|---|',
  ];

  for (const n of rulings) {
    const id = `R${String(n).padStart(2, '0')}`;
    const where = docs.get(n);
    const mine = cites.filter((c) => c.ruling === n);
    const first = mine[0];
    const cited = mine.length
      ? `\`${first!.path}:${first!.line}\`${mine.length > 1 ? ` +${mine.length - 1}` : ''}`
      : '—';
    lines.push(`| **${id}** | ${where ? `\`${where}\`` : '_at its citation_'} | ${cited} |`);
  }

  const orphans = rulings.filter((n) => !docs.has(n) && !cites.some((c) => c.ruling === n));
  lines.push('', orphans.length ? `Orphaned: ${orphans.join(', ')}` : 'No ruling is orphaned.', '');
  return lines.join('\n');
}

const wanted = render();
const path = join(ROOT, 'docs', 'RULINGS.md');

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(path, 'utf8');
  } catch {
    /* missing counts as stale */
  }
  if (current.replace(/\r\n/g, '\n') !== wanted) {
    console.error('docs/RULINGS.md is out of date. Run: npm run rulings');
    process.exit(1);
  }
  console.log('docs/RULINGS.md is current.');
} else {
  writeFileSync(path, wanted, 'utf8');
  console.log(`Wrote docs/RULINGS.md (${wanted.split('\n').length} lines).`);
}
